### ISSUE TITLE
Make open and close functions callable in components that require the accordion.

### ISSUE THREAD

**Issue by SpikeShape** [OpenSourceWorkflow/accordion#21]
Would it make sense to return the open and close functions to be used in other components that require the your accordion lib?
I found myself in a situation where I wanted to close other accordions within one .accordion context. But only in a certain situation so setting naturalBehaviour to true wouldn't be my way to go.

Adding an option to the parent .accordion to override the default behaviour that was declared when init function was called would be a possibility, too.

**Comment by markusfalk** [comment]
Sounds quite specific. Maybe just trigger 'click' on the corresponding header?

**Comment by SpikeShape** [comment]
That would work if I could trigger this click before the openAccordion function is called for the freshly clicked accordion header.
So we could also add some events like beforeOpen or beforeClose which I would be totally fine with.
